# Generated by Django 4.2.11 on 2026-04-25 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="loginhistory",
            name="is_suspicious",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="loginhistory",
            name="location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
