# Generated by Django 4.2.11 on 2026-04-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_customuser_failed_attempts_customuser_is_locked_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="lock_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
