# Generated by Django 4.2.11 on 2026-05-03 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_customuser_lock_until"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loginhistory",
            name="location",
        ),
    ]
